title: "Practico — Meditation & Sleep"
email: hi@praktika.app
description: "A non-esoteric meditation app. Your personal mindfulness guide who's always there. Helps you cope with stress, improve your sleep, and increase productivity."
domain: praktika.app
baseurl: ""
url: "https://praktika.app"

# Sass/SCSS settings
sass:
  sass_dir: _sass
  style: compressed

# Localization settings
languages: ["en", "pl", "ru"]
exclude_from_localizations: ["javascript", "js", "images", "css", "assets"]
default_locale_in_subfolder: false

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Plugins configuration
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2 # https://github.com/sverrirs/jekyll-paginate-v2
  - jekyll-loading-lazy # https://github.com/gildesmarais/jekyll-loading-lazy 
  - jekyll-multiple-languages-plugin # https://github.com/kurtsson/jekyll-multiple-languages-plugin
  - jekyll-target-blank #https://github.com/keithmifsud/jekyll-target-blank

# Posts defaults
defaults:
  - scope:
      path: "_i18n/ru/_posts"
      type: "posts"
    values:
      layout: "post"
      lang: "ru"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - script/

# SEO and social
social:
  facebook: practicoapp
  instagram: practicoapp
  
# Google Analytics
google_analytics: UA-140680835-1
google_analytics_4: G-FS0M8R7KHB

# Facebook settings
facebook_app_id: 1260724791513802
facebook_pixel_id: 386000906841885

# Yandex Metrika
yandex_metrika: 53745279

# App Store
app_store_id: 1467786415
